version: 0.2

env:
#   parameter-store: # if you are using parameter store to pass parameters.
#     BRANCH_NAME: "your-branch-parameter-name" #replace with your parameter name
#     ENVIRONMENT_NAME: "your-environment-parameter-name" #replace with your parameter name
#   # or if you are passing the parameters directly via codebuild environment variables
  variables:
    BRANCH_NAME: $BRANCH_NAME # codebuild will populate these
    ENVIRONMENT_NAME: $ENVIRONMENT_NAME #codebuild will populate these

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - echo "Building branch: $BRANCH_NAME"
      - echo "Building environment: $ENVIRONMENT_NAME"
      - dotnet publish -c Release -o ./build /p:BranchName="$BRANCH_NAME" /p:EnvironmentName="$ENVIRONMENT_NAME"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'build/**/*'
  discard-paths: yes

